import type { VehicleKind, VehicleStatus } from "./schema";

export type SeedVehicle = {
  slug: string;
  /** Omitido = carro, que e a maioria dos exemplos. */
  kind?: VehicleKind;
  brand: string;
  model: string;
  version: string;
  yearFab: number;
  year: number;
  price: number;
  mileage: number;
  transmission: string;
  fuel: string;
  color: string;
  doors: number;
  engine: string;
  plateEnd: string;
  /** Moto. Ficam zerados/vazios nos carros. */
  displacement?: number;
  gears?: number;
  startType?: string;
  brakes?: string;
  cooling?: string;
  ipvaPaid: boolean;
  oneOwner: boolean;
  inspection: boolean;
  status: VehicleStatus;
  features: string[];
  tags?: string[];
  description: string;
  /** Apenas as legendas: os arquivos entram no R2 pelo painel (fase 2). */
  photos: string[];
};

export const SEED_VEHICLES: SeedVehicle[] = [
  {
    slug: "chevrolet-onix-ltz-2023",
    brand: "Chevrolet",
    model: "Onix",
    version: "1.0 Turbo LTZ",
    yearFab: 2022,
    year: 2023,
    price: 89900,
    mileage: 38400,
    transmission: "Automático",
    fuel: "Flex",
    color: "Prata",
    doors: 4,
    engine: "1.0 Turbo 12V",
    plateEnd: "7",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      "Multimídia MyLink",
      "Câmera de ré",
      "Sensor de estacionamento",
      "Piloto automático",
      'Rodas de liga 16"',
      "Bancos em couro",
    ],
    description:
      "Onix LTZ turbo com revisões feitas na concessionária, todas registradas na agenda digital. Pneus trocados há 6 mil km e sem retoques de pintura. Aceito troca por carro de menor valor.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Interior",
      "Painel",
      "Rodas",
      "Porta-malas",
      "Motor",
    ],
  },
  {
    slug: "hyundai-hb20-platinum-2024",
    brand: "Hyundai",
    model: "HB20",
    version: "1.0 Turbo Platinum Plus",
    yearFab: 2023,
    year: 2024,
    price: 94500,
    mileage: 22100,
    transmission: "Automático",
    fuel: "Flex",
    color: "Branco",
    doors: 4,
    engine: "1.0 Turbo 12V",
    plateEnd: "2",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "novo",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      'Central multimídia 10"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Faróis full LED",
      "Teto solar",
      "Carregador por indução",
    ],
    description:
      "Chegou essa semana. Único dono, garantia de fábrica até 2029 e apenas 22 mil km rodados. Manual e as duas chaves em mãos.",
    photos: [
      "Frente",
      "Lateral direita",
      "Traseira",
      "Interior",
      "Painel",
      "Teto solar",
      "Porta-malas",
    ],
  },
  {
    slug: "honda-civic-exl-2020",
    brand: "Honda",
    model: "Civic",
    version: "EXL 2.0 CVT",
    yearFab: 2019,
    year: 2020,
    price: 118900,
    mileage: 61300,
    transmission: "CVT",
    fuel: "Flex",
    color: "Cinza",
    doors: 4,
    engine: "2.0 16V i-VTEC",
    plateEnd: "4",
    ipvaPaid: true,
    oneOwner: false,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      "Multimídia com CarPlay",
      "Câmera de ré",
      "Sensor de estacionamento",
      "Bancos em couro",
      'Rodas de liga 17"',
      "Chave presencial",
    ],
    description:
      "Civic EXL de segundo dono, sempre em garagem coberta. Revisão dos 60 mil km feita em abril, com troca de fluido do CVT e velas. Laudo cautelar aprovado, disponível para consulta.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Interior",
      "Painel",
      "Bancos traseiros",
      "Rodas",
      "Porta-malas",
      "Motor",
    ],
  },
  {
    slug: "toyota-corolla-xei-2022",
    brand: "Toyota",
    model: "Corolla",
    version: "XEi 2.0 Direct Shift",
    yearFab: 2021,
    year: 2022,
    price: 139900,
    mileage: 47800,
    transmission: "CVT",
    fuel: "Flex",
    color: "Preto",
    doors: 4,
    engine: "2.0 16V Dynamic Force",
    plateEnd: "9",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      'Multimídia 8"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Piloto adaptativo",
      "Bancos em couro",
      "Faróis LED",
    ],
    description:
      "Corolla XEi com histórico completo na Toyota e nota de todas as revisões. Nunca rodou em aplicativo. Pneus Michelin com 80% de vida útil.",
    photos: [
      "Frente",
      "Lateral direita",
      "Traseira",
      "Interior",
      "Painel",
      "Rodas",
      "Porta-malas",
    ],
  },
  {
    slug: "jeep-compass-longitude-2022",
    brand: "Jeep",
    model: "Compass",
    version: "Longitude 1.3 T270",
    yearFab: 2022,
    year: 2022,
    price: 149900,
    mileage: 54200,
    transmission: "Automático",
    fuel: "Flex",
    color: "Branco",
    doors: 4,
    engine: "1.3 Turbo T270",
    plateEnd: "1",
    ipvaPaid: true,
    oneOwner: false,
    inspection: true,
    status: "reservado",
    features: [
      "Ar-condicionado dual zone",
      "Direção elétrica",
      'Multimídia 10,1"',
      "Câmera de ré",
      "Sensor de estacionamento",
      'Rodas de liga 18"',
      "Faróis full LED",
      "Partida remota",
    ],
    description:
      "Compass Longitude reservado até sexta, com sinal pago. Se o negócio não se confirmar, volta para o catálogo. Aviso na hora quem estiver na lista.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Interior",
      "Painel",
      "Porta-malas",
      "Rodas",
    ],
  },
  {
    slug: "fiat-strada-volcano-2023",
    brand: "Fiat",
    model: "Strada",
    version: "Volcano 1.3 CD",
    yearFab: 2023,
    year: 2023,
    price: 112900,
    mileage: 29700,
    transmission: "Manual",
    fuel: "Flex",
    color: "Cinza",
    doors: 4,
    engine: "1.3 Firefly 8V",
    plateEnd: "5",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      'Multimídia 7"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Capota marítima",
      "Protetor de caçamba",
      'Rodas de liga 16"',
    ],
    description:
      "Strada cabine dupla usada só para trabalho leve, sem carga pesada na caçamba. Capota marítima e protetor instalados desde novos.",
    photos: [
      "Frente",
      "Lateral direita",
      "Caçamba",
      "Interior",
      "Painel",
      "Rodas",
      "Traseira",
    ],
  },
  {
    slug: "toyota-hilux-srv-2020",
    brand: "Toyota",
    model: "Hilux",
    version: "SRV 2.8 4x4 Diesel",
    yearFab: 2019,
    year: 2020,
    price: 229900,
    mileage: 118400,
    transmission: "Automático",
    fuel: "Diesel",
    color: "Prata",
    doors: 4,
    engine: "2.8 Turbo Diesel 16V",
    plateEnd: "3",
    ipvaPaid: true,
    oneOwner: false,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      'Multimídia 8"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Tração 4x4 reduzida",
      "Santo antônio",
      "Bancos em couro",
    ],
    description:
      "Hilux SRV de fazenda, sem uso em obra. Revisões de 10 em 10 mil km, últimas duas na Toyota de Piracicaba. Correias e filtros trocados aos 115 mil km.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Caçamba",
      "Interior",
      "Painel",
      "Motor",
      "Rodas",
    ],
  },
  {
    slug: "volkswagen-tcross-comfortline-2022",
    brand: "Volkswagen",
    model: "T-Cross",
    version: "Comfortline 200 TSI",
    yearFab: 2021,
    year: 2022,
    price: 124900,
    mileage: 43900,
    transmission: "Automático",
    fuel: "Flex",
    color: "Azul",
    doors: 4,
    engine: "1.0 TSI 12V",
    plateEnd: "8",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      'VW Play 10"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Piloto automático",
      "Bancos traseiros deslizantes",
      'Rodas de liga 17"',
    ],
    description:
      "T-Cross Comfortline de único dono, garantia VW válida até novembro. Pintura original em todas as peças, verificável no laudo.",
    photos: [
      "Frente",
      "Lateral direita",
      "Traseira",
      "Interior",
      "Painel",
      "Porta-malas",
    ],
  },
  {
    slug: "renault-kwid-intense-2024",
    brand: "Renault",
    model: "Kwid",
    version: "Intense 1.0 12V",
    yearFab: 2024,
    year: 2024,
    price: 68900,
    mileage: 12800,
    transmission: "Manual",
    fuel: "Flex",
    color: "Branco",
    doors: 4,
    engine: "1.0 SCe 12V",
    plateEnd: "6",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "novo",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      'Multimídia 8"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Vidros elétricos",
      'Rodas de liga 14"',
    ],
    description:
      "Kwid Intense praticamente zero, 12 mil km de uso urbano. Primeira revisão feita e garantia de fábrica em vigor até 2027. Ideal para primeiro carro.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Interior",
      "Painel",
      "Porta-malas",
    ],
  },
  {
    slug: "nissan-kicks-sv-2021",
    brand: "Nissan",
    model: "Kicks",
    version: "SV 1.6 CVT",
    yearFab: 2020,
    year: 2021,
    price: 96900,
    mileage: 72500,
    transmission: "CVT",
    fuel: "Flex",
    color: "Cinza",
    doors: 4,
    engine: "1.6 16V",
    plateEnd: "0",
    ipvaPaid: false,
    oneOwner: false,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      'Multimídia 8"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Faróis de LED",
      'Rodas de liga 17"',
    ],
    description:
      "Kicks SV bem conservado, com pequeno desgaste no acabamento do volante que mostro nas fotos. IPVA 2026 em aberto, já considerado no preço.",
    photos: [
      "Frente",
      "Lateral direita",
      "Traseira",
      "Interior",
      "Painel",
      "Rodas",
      "Porta-malas",
    ],
  },
  {
    slug: "ford-ranger-xlt-2019",
    brand: "Ford",
    model: "Ranger",
    version: "XLT 3.2 4x4 Diesel",
    yearFab: 2018,
    year: 2019,
    price: 189900,
    mileage: 141000,
    transmission: "Automático",
    fuel: "Diesel",
    color: "Preto",
    doors: 4,
    engine: "3.2 Turbo Diesel 20V",
    plateEnd: "4",
    ipvaPaid: true,
    oneOwner: false,
    inspection: true,
    status: "vendido",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      "SYNC 3",
      "Câmera de ré",
      "Sensor de estacionamento",
      "Tração 4x4",
      "Bancos em couro",
      "Capota rígida",
    ],
    description:
      "Vendida em janeiro. Mantenho o anúncio no ar como referência de histórico. Se procura uma picape diesel parecida, me chame que aviso quando entrar outra.",
    photos: [
      "Frente",
      "Lateral esquerda",
      "Traseira",
      "Caçamba",
      "Interior",
      "Painel",
    ],
  },
  {
    slug: "volkswagen-polo-highline-2023",
    brand: "Volkswagen",
    model: "Polo",
    version: "Highline 200 TSI",
    yearFab: 2022,
    year: 2023,
    price: 98900,
    mileage: 33200,
    transmission: "Automático",
    fuel: "Flex",
    color: "Prata",
    doors: 4,
    engine: "1.0 TSI 12V",
    plateEnd: "1",
    ipvaPaid: true,
    oneOwner: true,
    inspection: true,
    status: "disponivel",
    features: [
      "Ar-condicionado digital",
      "Direção elétrica",
      'VW Play 10"',
      "Câmera de ré",
      "Sensor de estacionamento",
      "Piloto automático",
      "Painel digital",
      'Rodas de liga 16"',
    ],
    description:
      "Polo Highline com painel digital e acabamento sem marcas de uso. Sempre abastecido com gasolina aditivada. Documentação em dia e transferência sem pendências.",
    photos: [
      "Frente",
      "Lateral direita",
      "Traseira",
      "Interior",
      "Painel",
      "Rodas",
      "Porta-malas",
    ],
  },
  {
    slug: "honda-cg-160-titan-2023",
    kind: "moto",
    brand: "Honda",
    model: "CG 160",
    version: "Titan Start",
    yearFab: 2022,
    year: 2023,
    price: 14900,
    mileage: 12400,
    transmission: "Manual",
    fuel: "Flex",
    color: "Vermelha",
    doors: 0,
    engine: "",
    plateEnd: "3",
    displacement: 162,
    gears: 5,
    startType: "Elétrica e pedal",
    brakes: "CBS (freio combinado)",
    cooling: "Ar",
    ipvaPaid: true,
    oneOwner: true,
    inspection: false,
    status: "disponivel",
    features: [
      "Partida elétrica",
      "Injeção eletrônica",
      "Alarme",
      "Baú / bagageiro",
      "Protetor de motor",
    ],
    tags: ["Pra trabalhar", "Aceito troca", "Revisada"],
    description:
      "CG 160 Titan de dono único, sempre revisada na concessionária. Pneus e relação trocados há 2 mil km, corrente regulada. Documento pago e pronta para transferir.",
    photos: ["Lateral direita", "Frente", "Painel", "Motor", "Traseira"],
  },
  {
    slug: "yamaha-fazer-250-2021",
    kind: "moto",
    brand: "Yamaha",
    model: "Fazer 250",
    version: "FZ25 ABS",
    yearFab: 2021,
    year: 2021,
    price: 19800,
    mileage: 21300,
    transmission: "Manual",
    fuel: "Gasolina",
    color: "Azul",
    doors: 0,
    engine: "",
    plateEnd: "8",
    displacement: 250,
    gears: 5,
    startType: "Elétrica",
    brakes: "ABS nas duas rodas",
    cooling: "Ar e óleo",
    ipvaPaid: true,
    oneOwner: false,
    inspection: true,
    status: "novo",
    features: [
      "Painel digital",
      "Farol de LED",
      "Injeção eletrônica",
      "Rodas de liga",
      "Suporte de celular",
    ],
    tags: ["Baixa quilometragem", "Pneus novos", "Financio com entrada"],
    description:
      "Fazer 250 com ABS nas duas rodas e painel digital. Nunca caiu, sem riscos na carenagem. Revisões feitas a cada 3 mil km, com nota. Aceito troca por moto de menor cilindrada.",
    photos: ["Lateral esquerda", "Frente", "Painel", "Escapamento", "Traseira", "Banco"],
  },
];
